Output docs/tapes/demo-quickstart.gif

Set Shell "bash"
Set FontSize 16
Set Width 1200
Set Height 800
Set Theme "Catppuccin Mocha"
Set Padding 24
Set CursorBlink false
Set TypingSpeed 70ms


Type "git clone https://github.com/timothysparg/gold"
Enter
Wait@30s

Type "cd gold"
Enter
Sleep 600ms

Type "mise trust"
Enter
Sleep 1600ms

Type "mise install"
Enter
Wait@1m

Type "mise build"
Enter
Wait@1m
